language: php
php:
  - '7.3'
  - '7.4'

env:
  - XDEBUG_MODE=coverage

before_script:
  - composer update

addons:
  sonarcloud:
    organization: "vctls-github"

script:
  - ./vendor/bin/phpunit
  - sonar-scanner

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./coverage.xml
